block
  plugin["Plugin"] space moduleEngine["Module Engine"]
  moduleEngine["Module Engine"] space formSetting["Form Setting"]
  plugin["Plugin"] --> moduleEngine["Module Engine"]
  moduleEngine["Module Engine"] --> formSetting["Form Setting"]
